services:
  mongo:
    image: mongo
    # restart: always
    # ports:
    #   - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: npm run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - auth
      - mongo

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: npm run start:dev payments
    env_file:
      - ./apps/payments/.env
    ports:
      - "3003:3003"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo

volumes:
  mongodb_data:
    driver: local
